# Generated by Django 2.2 on 2019-06-04 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheesename', models.CharField(max_length=255)),
                ('cheeseentrydate', models.DateField()),
                ('cheesedesc', models.TextField()),
                ('cheeseprice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'cheeses',
                'db_table': 'cheese',
            },
        ),
        migrations.CreateModel(
            name='CheeseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=50)),
                ('typedescription', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'cheesetypes',
                'db_table': 'cheesetype',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewtitle', models.CharField(max_length=255)),
                ('reviewdate', models.DateField()),
                ('reviewrating', models.SmallIntegerField()),
                ('reviewdesc', models.TextField()),
                ('cheese', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cheeseapp.Cheese')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'reviews',
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourcename', models.CharField(max_length=255)),
                ('resourcetype', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('dateentered', models.DateField()),
                ('description', models.TextField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'resources',
                'db_table': 'resource',
            },
        ),
        migrations.AddField(
            model_name='cheese',
            name='cheesetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cheeseapp.CheeseType'),
        ),
        migrations.AddField(
            model_name='cheese',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
