# Generated by Django 2.2 on 2019-06-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='dateentered',
            field=models.DateField(blank=True),
        ),
    ]
