# Generated by Django 2.2 on 2019-06-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeseapp', '0003_auto_20190611_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheese',
            name='cheeseentrydate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='dateentered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
